### PR TITLE
Yield details visibility should be consistent for Fixed/Variable - closes #990

### LINKED ISSUE #990: Yield details visibility should be consistent for Fixed/Variable
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand YFI.
3. Manage.
4. Pick YFI in "From" dropdown box.
5. Type in "0" amount.

Expected:
The Variable Yield details should be the same as Fixed Yield details.

Actual:
image

### PR DESCRIPTION
**Pull request by danieledamiani**

### CODE REVIEW

File: packages/tempus-client_v2/src/components/deposit/Deposit.tsx [hunk 1]
```diff
@@ -670,6 +668,7 @@ const Deposit: FC<DepositProps> = ({ narrow, chain }) => {
 
   const estimatedYieldAtMaturityFormatted = useMemo(() => {
     if (!estimatedYieldAtMaturity) {
+      console.log('here 2a ======>');
```
Comment (lazarmitic) [inline packages/tempus-client_v2/src/components/deposit/Deposit.tsx:671]: Remove console log.

**Review by lazarmitic — CHANGES_REQUESTED** [review]

File: packages/tempus-client_v2/src/components/deposit/Deposit.tsx (hunk 1 above)
Comment (danieledamiani) [reply packages/tempus-client_v2/src/components/deposit/Deposit.tsx]: done

**Review by lazarmitic — APPROVED** [review]
